INFO:rabbit_client:Message is valid.
INFO:rabbit_client:https://europe.api.riotgames.com/riot/account/v1/accounts/by-riot-id/KyattPL/EUW?api_key=RGAPI-54fe163f-f193-4515-96ba-9575e9139eb9
INFO:rabbit_client:https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/0aKzTFIR_wlqL0Al5O-nItmFGsdNsIwql3gzgEsaH5kvRq91tTFNErlL7OMLqfReUCKWSmnTEmyKSg/ids?api_key=RGAPI-54fe163f-f193-4515-96ba-9575e9139eb9&type=ranked
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:https://europe.api.riotgames.com/riot/account/v1/accounts/by-riot-id/KyattPL/EUW?api_key=RGAPI-54fe163f-f193-4515-96ba-9575e9139eb9
INFO:rabbit_client:https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/0aKzTFIR_wlqL0Al5O-nItmFGsdNsIwql3gzgEsaH5kvRq91tTFNErlL7OMLqfReUCKWSmnTEmyKSg/ids?api_key=RGAPI-54fe163f-f193-4515-96ba-9575e9139eb9&type=ranked
INFO:rabbit_client:Message is valid.
ERROR:aiormq.connection:Unexpected connection close from remote "amqp://guest:******@localhost:5672//", Connection.Close(reply_code=320, reply_text="CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
NoneType: None
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: Server connection unexpectedly closed. Read 0 bytes but 1 bytes expected. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: Server connection unexpectedly closed. Read 0 bytes but 1 bytes expected. Reconnecting after 5 seconds.
