INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
INFO:rabbit_client:Message is valid.
ERROR:aiormq.connection:Unexpected connection close from remote "amqp://guest:******@localhost:5672//", Connection.Close(reply_code=320, reply_text="CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
NoneType: None
ERROR:aiormq.connection:Unexpected connection close from remote "amqp://guest:******@localhost:5672//", Connection.Close(reply_code=320, reply_text="CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
NoneType: None
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: Server connection unexpectedly closed. Read 0 bytes but 1 bytes expected. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: Server connection unexpectedly closed. Read 0 bytes but 1 bytes expected. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: Server connection unexpectedly closed. Read 0 bytes but 1 bytes expected. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: Server connection unexpectedly closed. Read 0 bytes but 1 bytes expected. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: [WinError 1225] Komputer zdalny odrzuci³ po³¹czenie sieciowe. Reconnecting after 5 seconds.
INFO:aio_pika.robust_connection:Connection to amqp://guest:******@localhost:5672// closed. Reconnecting after 5 seconds.
WARNING:aio_pika.robust_connection:Connection attempt to "amqp://guest:******@localhost:5672//" failed: [WinError 1225] Komputer zdalny odrzuci³ po³¹czenie sieciowe. Reconnecting after 5 seconds.
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Próbowano przeprowadziæ próbê na obiekcie, który nie jest gniazdem
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Próbowano przeprowadziæ próbê na obiekcie, który nie jest gniazdem
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Próbowano przeprowadziæ próbê na obiekcie, który nie jest gniazdem
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Próbowano przeprowadziæ próbê na obiekcie, który nie jest gniazdem
